APP_NAMESPACE = "ticket_bot"
SCHEMA_VERSION_TABLE = "schema_version"
CURRENT_SCHEMA_VERSION = 14

DEFAULT_GUILD_TIMEZONE = "UTC"
CUSTOM_ID_SEPARATOR = ":"

PANEL_CUSTOM_ID_PREFIX = "panel"
TICKET_CUSTOM_ID_PREFIX = "ticket"
STAFF_CUSTOM_ID_PREFIX = "staff"

DRAFT_INACTIVE_CLOSE_HOURS = 6
DRAFT_INACTIVE_WARNING_HOURS = 5
DRAFT_ABANDON_TIMEOUT_HOURS = 24
DRAFT_ABANDON_WARNING_HOURS = 23
SLEEP_CHANNEL_PREFIX = "💤|"
TRANSFER_EXECUTION_DELAY_SECONDS = 300
CLOSE_REVOKE_WINDOW_SECONDS = 120
CLOSE_REQUEST_TIMEOUT_SECONDS = 300
SNAPSHOT_CREATE_WARNING_THRESHOLD = 900
SNAPSHOT_CREATE_LIMIT = 1000
