APP_NAMESPACE = "ticket_bot"
SCHEMA_VERSION_TABLE = "schema_version"
CURRENT_SCHEMA_VERSION = 2

DEFAULT_GUILD_TIMEZONE = "UTC"
CUSTOM_ID_SEPARATOR = ":"

PANEL_CUSTOM_ID_PREFIX = "panel"
TICKET_CUSTOM_ID_PREFIX = "ticket"
STAFF_CUSTOM_ID_PREFIX = "staff"

DRAFT_INACTIVE_CLOSE_HOURS = 6
DRAFT_ABANDON_TIMEOUT_HOURS = 24
